# Generated by Django 2.2.2 on 2019-06-17 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_film_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='poster',
            field=models.ImageField(default=None, upload_to='posters'),
        ),
        migrations.AlterField(
            model_name='film',
            name='description',
            field=models.TextField(default=None),
        ),
    ]
